feat(install): add 1password-cli install flow

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -2,19 +2,20 @@
 
 set -euo pipefail
 
-# shellcheck source=../lib/utils.bash
+# shellcheck source=lib/utils.bash
 source "$(dirname "$0")/../lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+# This to proper extension and adapt extracting strategy.
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION"
 
 # Download tar.gz file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
-
-# Remove the tar.gz file since we don't need to keep it
-rm "$release_file"
+platform=$(get_platform)
+if [ "$platform" != "darwin" ]; then
+  unzip "$release_file.zip" -d "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+  # Remove download file since we don't need to keep it
+  rm "$release_file.zip"
+fi
